version: '3'

dotenv:
  - .env

interval: 500ms

tasks:
  build:
    cmds:
      - go install
    sources:
      - '**/*.go'
    watch: true

  example-apply:
    cmds:
      - terraform plan
      - terraform apply
    dir: examples/provider

  example-destroy:
    cmds:
      - terraform destroy
    dir: examples/provider

  example-import:
    cmds:
      - terraform state rm ketryx_project.test
      - terraform import ketryx_project.test KXPRJ01KWC7PQHBEXZSZAY0HN5TMAQT
      - terraform plan
    dir: examples/provider
