version: '3'

dotenv:
  - .env

interval: 500ms

tasks:
  build:
    cmds:
      - go install
    sources:
      - '**/*.go'
    watch: true

  example:
    cmds:
      - terraform plan
      - terraform apply
    dir: examples/provider
